M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 17, Monday 18:55:53
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-17T18:55:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.0945Y-1.4567
X4.0945Y-5.9055
X8.4646Y-5.9449
X8.8583Y-1.4567
T0
M30
