M48
; DRILL file {KiCad 7.0.1-0} date 2023 April 17, Monday 18:47:54
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-17T18:47:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.4646Y-1.938
X4.4646Y-8.697
X12.7717Y-1.938
X12.7717Y-8.697
T0
M30
